- name: Check for Signing key
  become: true
  register: key
  stat: 
    path: /usr/share/keyrings/hashicorp-archive-keyring.gpg

- name: Install Signing key
  when: not key.stat.exists
  become: true
  shell: wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg

- name: Ensure Repo
  become: true
  shell: echo "deb [arch=`dpkg --print-architecture` signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
  
- name: Update Software
  become: true
  apt:
    update_cache: true
    name: "*"
    state: latest