# Note that this file is autogenerated from hosts.tpl. Do not change anything in the output manually as it will be overwritten


%{ for tagkind in toset(flatten([for n in pm1: n.tags])) ~}
[${tagkind}]
%{ for m1 in pm1 ~}
%{ if contains(m1.tags, tagkind) ~}
${m1.hostname} 
%{ endif ~}
%{ endfor ~}

%{ endfor ~}

[all]
%{ for m1 in pm1 ~}
${m1.hostname} ansible_host="${m1.ip}" diskconfig='${jsonencode(m1.diskConfig)}' hosttags='${jsonencode(m1.tags)}' cfg='${m1.extraVars}'
%{ endfor ~}
%{ for m1 in on1 ~}
${m1.hostname} ansible_host="${m1.ip}" ${m1.extraVars}
%{ endfor ~}